version: '3.3'
services:
  mysql-db:
      build:
        context: ./db
      container_name: mysql_container
      environment:
        MYSQL_ROOT_PASSWORD: password 
        MYSQL_DATABASE: 5mrruYpkTT         
        MYSQL_USER: user
        MYSQL_PASSWORD: password   
        MYSQL_HOST: localhost 
      ports:
        - 3306:3306
      restart: unless-stopped
      volumes:
        - ./db_data/:/var/lib/mysql/             
        - ./db/5mrruYpkTT.sql:/docker-entrypoint-initdb.d/5mrruYpkTT.sql
        - ./db/backup/files/:/data_backup/data
 
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: password      
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always        

  web:
    build:
      context: ./app
    volumes:
      - .:/app/api
    command: npm run start
    depends_on:
      - mysql-db     
    ports:
      - 5010:5010
    container_name: node_js  
    links:
      - mysql-db        
    environment:
      VIRTUAL_HOST: iset.rades
      VIRTUAL_PORT: 4200
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

volumes: 
  db-config:
  db-data: